# Generated by Django 3.2.11 on 2022-01-26 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220126_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('radius', models.IntegerField(default=0)),
                ('color', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_userprofile', to='accounts.userprofile')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_locations', to='accounts.location')),
                ('specialties', models.ManyToManyField(related_name='doc_specialty', to='accounts.Specialty')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='specialties',
            field=models.ManyToManyField(related_name='loc_specialty', to='accounts.Specialty'),
        ),
    ]
