# Generated by Django 3.2.11 on 2022-01-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_userprofile_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='location',
            name='post_code',
            field=models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Post Code'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='State'),
        ),
    ]
