# Generated by Django 3.2.11 on 2022-01-28 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20220128_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.TextField(null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('given_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_userprofile', to='accounts.provider')),
            ],
        ),
    ]
