# Generated by Django 3.2.11 on 2022-01-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='review_percentage',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
