# Generated by Django 3.2.11 on 2022-01-28 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_provider_review_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherlocations',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_locations', to='accounts.location'),
        ),
    ]
