# Generated by Django 3.2.11 on 2022-01-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_otherlocations_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address2',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address2'),
        ),
        migrations.AddField(
            model_name='provider',
            name='office_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address1'),
        ),
    ]
