# Generated by Django 3.2.11 on 2022-01-30 09:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0013_auto_20220129_1726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='Firm',
        ),
    ]
