# Generated by Django 3.2.11 on 2022-01-30 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_provider_firm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firm',
            name='description',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='fb_page',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='google_page',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='review_percentage',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='twitter_page',
        ),
        migrations.RemoveField(
            model_name='firm',
            name='website',
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('fb_page', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('twitter_page', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('google_page', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('review_percentage', models.IntegerField(default=0, null=True)),
                ('providerprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_userprofile', to='accounts.firm')),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_userprofile', to='accounts.provider'),
        ),
        migrations.AlterField(
            model_name='location',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_userprofile', to='accounts.provider'),
        ),
        migrations.AlterField(
            model_name='review',
            name='given_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_userprofile', to='accounts.provider'),
        ),
    ]
