# Generated by Django 3.2.11 on 2022-01-30 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20220130_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attorneyprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attorney_userprofile', to='accounts.firm')),
                ('blacklist', models.ManyToManyField(related_name='black_providers', to='accounts.Provider')),
                ('favorites', models.ManyToManyField(related_name='fav_providers', to='accounts.Provider')),
                ('flag', models.ManyToManyField(related_name='flag_providers', to='accounts.Provider')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='given_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_attorney', to='accounts.attorney'),
        ),
    ]
