# Generated by Django 3.2.11 on 2022-01-30 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_firm_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttorneyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address1')),
                ('address2', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address2')),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='State')),
                ('post_code', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Post Code')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_attorney', to='accounts.attorney')),
            ],
        ),
    ]
