# Generated by Django 3.2.11 on 2022-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220130_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorneylocation',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Country'),
        ),
    ]
