# Generated by Django 3.2.11 on 2022-01-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_attorneylocation_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='post_as',
            field=models.CharField(default='0', max_length=255),
        ),
    ]
