# Generated by Django 3.2.11 on 2022-01-31 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_review_post_as'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='blacklist',
        ),
        migrations.AddField(
            model_name='attorney',
            name='blacklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='black_providers', to='accounts.provider'),
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='favorites',
        ),
        migrations.AddField(
            model_name='attorney',
            name='favorites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_providers', to='accounts.provider'),
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='flag',
        ),
        migrations.AddField(
            model_name='attorney',
            name='flag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flag_providers', to='accounts.provider'),
        ),
        migrations.RemoveField(
            model_name='marketer',
            name='blacklist',
        ),
        migrations.AddField(
            model_name='marketer',
            name='blacklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blackmarketer_providers', to='accounts.provider'),
        ),
        migrations.RemoveField(
            model_name='marketer',
            name='favorites',
        ),
        migrations.AddField(
            model_name='marketer',
            name='favorites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favmarketer_providers', to='accounts.provider'),
        ),
        migrations.RemoveField(
            model_name='marketer',
            name='flag',
        ),
        migrations.AddField(
            model_name='marketer',
            name='flag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flagmarketer_providers', to='accounts.provider'),
        ),
    ]
