# Generated by Django 3.2.11 on 2022-01-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20220131_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='blacklist',
        ),
        migrations.AddField(
            model_name='attorney',
            name='blacklist',
            field=models.ManyToManyField(related_name='black_providers', to='accounts.Provider'),
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='favorites',
        ),
        migrations.AddField(
            model_name='attorney',
            name='favorites',
            field=models.ManyToManyField(related_name='fav_providers', to='accounts.Provider'),
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='flag',
        ),
        migrations.AddField(
            model_name='attorney',
            name='flag',
            field=models.ManyToManyField(related_name='flag_providers', to='accounts.Provider'),
        ),
        migrations.RemoveField(
            model_name='marketer',
            name='blacklist',
        ),
        migrations.AddField(
            model_name='marketer',
            name='blacklist',
            field=models.ManyToManyField(related_name='blackmarketer_providers', to='accounts.Provider'),
        ),
        migrations.RemoveField(
            model_name='marketer',
            name='favorites',
        ),
        migrations.AddField(
            model_name='marketer',
            name='favorites',
            field=models.ManyToManyField(related_name='favmarketer_providers', to='accounts.Provider'),
        ),
        migrations.RemoveField(
            model_name='marketer',
            name='flag',
        ),
        migrations.AddField(
            model_name='marketer',
            name='flag',
            field=models.ManyToManyField(related_name='flagmarketer_providers', to='accounts.Provider'),
        ),
    ]
