# Generated by Django 3.2.11 on 2022-02-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20220201_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorney',
            name='marketer_codes',
        ),
        migrations.AddField(
            model_name='marketer',
            name='marketer_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='MarketerCode',
        ),
    ]
