# Generated by Django 3.2.11 on 2022-02-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20220201_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='marketer_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
