# Generated by Django 3.2.11 on 2022-02-01 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_attorney_marketer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flagged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.provider')),
            ],
        ),
        migrations.AlterField(
            model_name='attorney',
            name='flag',
            field=models.ManyToManyField(related_name='flag_providers', to='accounts.Flagged'),
        ),
    ]
