# Generated by Django 3.2.11 on 2022-02-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_auto_20220202_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerstaff',
            name='account_type',
            field=models.CharField(default='ProviderStaff', max_length=255),
        ),
    ]
