# Generated by Django 3.2.11 on 2022-02-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_attorneystaff_marketerstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialty',
            name='secondary_color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
