# Generated by Django 3.2.11 on 2022-03-11 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_specialty_secondary_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherlocations',
            name='location',
        ),
        migrations.AddField(
            model_name='otherlocations',
            name='for_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_locations', to='accounts.provider'),
        ),
    ]
