# Generated by Django 3.2.11 on 2022-04-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20220311_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerstaff',
            name='permission',
            field=models.CharField(blank=True, default='No', max_length=255, null=True),
        ),
    ]
