# Generated by Django 3.2.11 on 2022-05-26 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_providerstaff_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFTreatmentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('second_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('visits', models.IntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_tf', to='accounts.provider')),
            ],
        ),
    ]
