# Generated by Django 3.2.11 on 2022-05-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0180_case_created_by'),
        ('accounts', '0042_tftreatmentdate_for_case_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tftreatmentdate',
            name='for_case_provider',
        ),
        migrations.AddField(
            model_name='tftreatmentdate',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_tftreatmentdate', to='BP.case'),
        ),
    ]
