# Generated by Django 3.2.11 on 2022-05-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_tftreatmentdate_for_case_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tftreatmentdate',
            name='visits',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
