# Generated by Django 3.2.11 on 2022-05-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_tftreatmentdate_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tftreatmentdate',
            name='first_date',
            field=models.CharField(blank=True, default='_/_/_', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tftreatmentdate',
            name='second_date',
            field=models.CharField(blank=True, default='_/_/_', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tftreatmentdate',
            name='visits',
            field=models.CharField(blank=True, default='__', max_length=255, null=True),
        ),
    ]
