# Generated by Django 3.2.11 on 2022-05-31 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0183_auto_20220601_0357'),
        ('accounts', '0046_auto_20220527_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hi_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hi_reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mp_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by_tf_accounting', to='accounts.provider')),
                ('for_case_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_provider_accounting', to='BP.caseproviders')),
            ],
        ),
    ]
