# Generated by Django 3.2.11 on 2022-05-31 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0183_auto_20220601_0357'),
        ('accounts', '0047_tfaccounting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfaccounting',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_tfaccounting', to='BP.case'),
        ),
    ]
