# Generated by Django 3.2.11 on 2022-06-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_auto_20220601_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfaccounting',
            name='payment_received_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
