# Generated by Django 3.2.11 on 2022-06-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_tfcasestatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tfcasestatus',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='tfcasestatus',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
