# Generated by Django 3.2.11 on 2022-06-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20220602_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfaccounting',
            name='payment_received_date',
            field=models.CharField(blank=True, default='_/_/_', max_length=255, null=True),
        ),
    ]
