# Generated by Django 3.2.11 on 2022-06-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20220605_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherlocations',
            name='address',
        ),
        migrations.RemoveField(
            model_name='otherlocations',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='otherlocations',
            name='city',
        ),
        migrations.RemoveField(
            model_name='otherlocations',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='otherlocations',
            name='state',
        ),
        migrations.AddField(
            model_name='otherlocations',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
