# Generated by Django 3.2.11 on 2022-06-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20220605_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfaccounting',
            name='check_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tfaccounting',
            name='patient_payment_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
