# Generated by Django 3.2.11 on 2022-07-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_tfdoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfaccounting',
            name='liens',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
