# Generated by Django 3.2.11 on 2022-07-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_tfaccounting_liens'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfaccounting',
            name='payments',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tfaccounting',
            name='reductions',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
