# Generated by Django 3.2.11 on 2022-02-13 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attorney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketer_code', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='NA', max_length=200)),
                ('account_type', models.CharField(default='', max_length=100)),
                ('office_name', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bp_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttorneyStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(default='AttorneyStaff', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BP.attorney')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_attorneystaff_userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttorneyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address1')),
                ('address2', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address2')),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='State')),
                ('post_code', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Post Code')),
                ('country', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Country')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('fax', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fax')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_location_attorney', to='BP.attorney')),
            ],
        ),
        migrations.AddField(
            model_name='attorney',
            name='attorneyprofile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_attorney_userprofile', to='BP.firm'),
        ),
    ]
