# Generated by Django 3.2.11 on 2022-02-15 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthday',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='ClientLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address1')),
                ('address2', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Address2')),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='State')),
                ('post_code', models.CharField(blank=True, default='', max_length=8, null=True, verbose_name='Post Code')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_location_Client', to='BP.client')),
            ],
        ),
    ]
