# Generated by Django 3.2.11 on 2022-02-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0003_auto_20220216_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_clients_attorney', to='BP.attorney'),
        ),
    ]
