# Generated by Django 3.2.11 on 2022-02-16 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_specialty_secondary_color'),
        ('BP', '0005_clientproviders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientproviders',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_provider_location', to='accounts.location'),
        ),
        migrations.AlterField(
            model_name='clientproviders',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bp_provider_specialty', to='accounts.specialty'),
        ),
    ]
