# Generated by Django 3.2.11 on 2022-02-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0009_auto_20220218_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='court_jurisdiction',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='date_closed',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
