# Generated by Django 3.2.11 on 2022-02-18 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0011_case_case_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='added_by',
            new_name='created_by',
        ),
        migrations.AddField(
            model_name='notes',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_notes', to='BP.case'),
        ),
    ]
