# Generated by Django 3.2.11 on 2022-02-18 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0012_auto_20220219_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.attorney'),
        ),
    ]
