# Generated by Django 3.2.11 on 2022-02-20 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0013_alter_notes_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defendant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('birthday', models.CharField(default='', max_length=255)),
                ('ssn', models.CharField(default='', max_length=255)),
                ('driver_license', models.CharField(default='', max_length=255)),
                ('age', models.CharField(default='', max_length=255)),
                ('note', models.CharField(default='', max_length=255)),
                ('for_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_defendants', to='BP.case')),
                ('for_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client')),
            ],
        ),
    ]
