# Generated by Django 3.2.11 on 2022-02-21 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0017_insurance'),
    ]

    operations = [
        migrations.CreateModel(
            name='carAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='', max_length=255)),
                ('date', models.CharField(default='', max_length=255)),
                ('time', models.CharField(default='', max_length=255)),
                ('weather', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('for_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_caraccident', to='BP.case')),
                ('for_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client')),
            ],
        ),
    ]
