# Generated by Django 3.2.11 on 2022-02-21 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0019_auto_20220222_0057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Litigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jurisdiction', models.CharField(default='', max_length=255)),
                ('case_name', models.CharField(default='', max_length=255)),
                ('case_number', models.CharField(default='', max_length=255)),
                ('court_name', models.CharField(default='', max_length=255)),
                ('address', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
