# Generated by Django 3.2.11 on 2022-02-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0020_litigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_litigation', to='BP.case'),
        ),
        migrations.AddField(
            model_name='litigation',
            name='for_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client'),
        ),
    ]
