# Generated by Django 3.2.11 on 2022-02-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0022_auto_20220222_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigation',
            name='case_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='case_number',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='county',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='court_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='federal_court',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='jurisdiction',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='state',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
