# Generated by Django 3.2.11 on 2022-02-22 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0023_auto_20220222_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='total_visits',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='visit_from',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='visit_to',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
