# Generated by Django 3.2.11 on 2022-02-22 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0024_auto_20220222_0518'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', null=True)),
                ('date', models.CharField(default='', max_length=100, null=True)),
                ('for_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_treatment_notes', to='BP.caseproviders')),
            ],
        ),
    ]
