# Generated by Django 3.2.11 on 2022-02-25 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0026_auto_20220224_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='defendant',
            name='defendant_type',
            field=models.CharField(default='Private Individual', max_length=255),
        ),
        migrations.CreateModel(
            name='Statute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statute_date', models.CharField(default='', max_length=255)),
                ('for_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_statutes', to='BP.case')),
                ('for_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client')),
                ('for_defendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defendant_statutes', to='BP.case')),
            ],
        ),
    ]
