# Generated by Django 3.2.11 on 2022-02-25 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0027_auto_20220226_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='caraccident',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='caraccident',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
