# Generated by Django 3.2.11 on 2022-02-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0028_auto_20220226_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='defendant',
            name='statute_date',
            field=models.CharField(default='', max_length=255),
        ),
    ]
