# Generated by Django 3.2.11 on 2022-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0029_defendant_statute_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statute',
            name='statute_date',
            field=models.DateTimeField(default=''),
        ),
    ]
