# Generated by Django 3.2.11 on 2022-02-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0031_auto_20220226_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
