# Generated by Django 3.2.11 on 2022-02-28 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0032_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='document_type',
            field=models.CharField(default='Medical Treatment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='file_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_files', to='BP.case'),
        ),
        migrations.AddField(
            model_name='doc',
            name='for_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client'),
        ),
    ]
