# Generated by Django 3.2.11 on 2022-03-02 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0033_auto_20220228_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlaggedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_on', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm_flaggedcases', to='BP.firm')),
                ('for_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_flaggedpages', to='BP.case')),
                ('for_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client')),
            ],
        ),
    ]
