# Generated by Django 3.2.11 on 2022-03-02 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BP', '0034_flaggedpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flaggedpage',
            name='flagged_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm_flaggedcases', to=settings.AUTH_USER_MODEL),
        ),
    ]
