# Generated by Django 3.2.11 on 2022-03-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0035_alter_flaggedpage_flagged_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedpage',
            name='page_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
