# Generated by Django 3.2.11 on 2022-03-02 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0036_flaggedpage_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flaggedpage',
            name='page_link',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
