# Generated by Django 3.2.11 on 2022-03-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0037_flaggedpage_page_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='document_type',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='upload',
            field=models.FileField(upload_to='images/'),
        ),
    ]
