# Generated by Django 3.2.11 on 2022-03-04 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0038_auto_20220304_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='document_no',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doc',
            name='page_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='document',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='note_doc', to='BP.doc'),
        ),
    ]
