# Generated by Django 3.2.11 on 2022-03-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0039_auto_20220304_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='check',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
