# Generated by Django 3.2.11 on 2022-03-04 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0040_doc_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='upload',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
