# Generated by Django 3.2.11 on 2022-03-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0045_doc_provider_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('payee', models.CharField(default='', max_length=255, null=True)),
                ('invoice_number', models.IntegerField(null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('paid_by', models.CharField(default='', max_length=255, null=True)),
                ('check_number', models.IntegerField(null=True)),
                ('check_date', models.CharField(default='', max_length=255, null=True)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
