# Generated by Django 3.2.11 on 2022-03-06 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0046_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_costs', to='BP.case'),
        ),
        migrations.AddField(
            model_name='costs',
            name='for_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client'),
        ),
    ]
