# Generated by Django 3.2.11 on 2022-03-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0047_auto_20220307_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costs',
            name='date',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
