# Generated by Django 3.2.11 on 2022-03-06 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BP', '0048_alter_costs_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='user_type',
            field=models.CharField(default='Attorney', max_length=255),
        ),
        migrations.AddField(
            model_name='attorneystaff',
            name='user_type',
            field=models.CharField(default='case manager', max_length=255),
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.CharField(default='', max_length=255, null=True)),
                ('user_type', models.CharField(default='', max_length=255, null=True)),
                ('todo_type', models.CharField(default='', max_length=255, null=True)),
                ('created_by', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_users', to=settings.AUTH_USER_MODEL)),
                ('for_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_costs', to='BP.case')),
                ('for_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client')),
            ],
        ),
    ]
