# Generated by Django 3.2.11 on 2022-03-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0050_alter_todo_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='notes',
            field=models.CharField(default='N/A', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.CharField(default='Not Completed', max_length=255, null=True),
        ),
    ]
