# Generated by Django 3.2.11 on 2022-03-07 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0051_auto_20220307_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attorney',
            name='user_type',
            field=models.CharField(default='attorney', max_length=255),
        ),
    ]
