# Generated by Django 3.2.11 on 2022-03-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0053_alter_costs_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_at',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='completed_note',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
