# Generated by Django 3.2.11 on 2022-03-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0055_costs_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
