# Generated by Django 3.2.11 on 2022-03-13 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0059_auto_20220313_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_statuses', to='BP.clientstatus'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(default='New Lead', max_length=100, null=True),
        ),
    ]
