# Generated by Django 3.2.11 on 2022-03-13 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0060_auto_20220313_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='status',
        ),
    ]
