# Generated by Django 3.2.11 on 2022-03-13 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0062_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='status',
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_statuses', to='BP.clientstatus'),
        ),
    ]
