# Generated by Django 3.2.11 on 2022-03-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0063_auto_20220313_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='open',
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(default='New Lead', max_length=100, null=True),
        ),
    ]
