# Generated by Django 3.2.11 on 2022-03-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0066_case_firm_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorneystaff',
            name='phone_extension',
            field=models.CharField(default='', max_length=255),
        ),
    ]
