# Generated by Django 3.2.11 on 2022-03-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0067_attorneystaff_phone_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='firm_users',
        ),
        migrations.AddField(
            model_name='case',
            name='firm_users',
            field=models.ManyToManyField(related_name='firmusers_cases', to='BP.AttorneyStaff'),
        ),
    ]
