# Generated by Django 3.2.11 on 2022-03-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0068_auto_20220317_0508'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttorneyUserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='attorney',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='attorneystaff',
            name='user_type',
        ),
        migrations.AddField(
            model_name='attorney',
            name='user_type',
            field=models.ManyToManyField(to='BP.AttorneyUserType'),
        ),
        migrations.AddField(
            model_name='attorneystaff',
            name='user_type',
            field=models.ManyToManyField(to='BP.AttorneyUserType'),
        ),
    ]
