# Generated by Django 3.2.11 on 2022-03-17 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0071_lettertemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lettertemplate',
            old_name='category',
            new_name='template_name',
        ),
    ]
