# Generated by Django 3.2.11 on 2022-03-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0072_rename_category_lettertemplate_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('value', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
