# Generated by Django 3.2.11 on 2022-03-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0073_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettertemplate',
            name='template_type',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
