# Generated by Django 3.2.11 on 2022-03-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0074_lettertemplate_template_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defendant',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='otherparty',
            old_name='address',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='witness',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='defendant',
            name='address2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='defendant',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='defendant',
            name='post_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='defendant',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherparty',
            name='address2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherparty',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherparty',
            name='post_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherparty',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='address2',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='post_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
    ]
