# Generated by Django 3.2.11 on 2022-03-20 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0075_auto_20220321_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defendant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='otherparty',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='witness',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='defendant',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherparty',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
