# Generated by Django 3.2.11 on 2022-03-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0077_casechecklist_checklist_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casechecklist',
            name='checklist',
        ),
        migrations.AddField(
            model_name='casechecklist',
            name='checklist',
            field=models.ManyToManyField(null=True, related_name='orignalchecklist_case', to='BP.CheckList'),
        ),
    ]
