# Generated by Django 3.2.11 on 2022-03-26 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0080_case_tf_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='tf_case_status',
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='tf_case_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tf_case_statuses', to='BP.clientstatus'),
        ),
    ]
