# Generated by Django 3.2.11 on 2022-03-27 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0081_auto_20220326_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelCheckList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_name', models.CharField(default='', max_length=255, null=True)),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PanelCaseChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, null=True)),
                ('checklist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panelorignalchecklist_case', to='BP.panelchecklist')),
                ('for_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_panel_checklists', to='BP.case')),
                ('for_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client')),
                ('for_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.caseproviders')),
            ],
        ),
    ]
