# Generated by Django 3.2.11 on 2022-03-27 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0082_panelcasechecklist_panelchecklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panelchecklist',
            name='panel_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panel_checklist_page', to='BP.page'),
        ),
    ]
