# Generated by Django 3.2.11 on 2022-04-05 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0083_alter_panelchecklist_panel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='department',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='litigation',
            name='department_contact',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='litigation',
            name='judge_contact',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='litigation',
            name='judge_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='for_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_notes', to='BP.client'),
        ),
    ]
