# Generated by Django 3.2.11 on 2022-04-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0084_auto_20220405_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.CharField(default='', max_length=255, null=True)),
                ('loan_company', models.CharField(default='', max_length=255, null=True)),
                ('contact_name', models.CharField(default='', max_length=255, null=True)),
                ('phone', models.CharField(default='', max_length=255, null=True)),
                ('address1', models.CharField(default='', max_length=255, null=True)),
                ('address2', models.CharField(default='', max_length=255, null=True)),
                ('city', models.CharField(default='', max_length=255, null=True)),
                ('state', models.CharField(default='', max_length=255, null=True)),
                ('zip_code', models.CharField(default='', max_length=255, null=True)),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('loan_amount', models.CharField(default='', max_length=255, null=True)),
                ('fees', models.IntegerField(default=0, null=True)),
                ('status', models.CharField(default='', max_length=255, null=True)),
                ('interest', models.CharField(default='', max_length=255, null=True)),
                ('amount_estimate', models.IntegerField(default=0, null=True)),
                ('for_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_case_loans', to='BP.case')),
                ('for_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client')),
            ],
        ),
    ]
