# Generated by Django 3.2.11 on 2022-04-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0085_caseloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporting_agency', models.CharField(default='', max_length=255, null=True)),
                ('reporting_officer', models.CharField(default='', max_length=255, null=True)),
                ('address1', models.CharField(default='', max_length=255, null=True)),
                ('address2', models.CharField(default='', max_length=255, null=True)),
                ('city', models.CharField(default='', max_length=255, null=True)),
                ('state', models.CharField(default='', max_length=255, null=True)),
                ('zip_code', models.CharField(default='', max_length=255, null=True)),
                ('report_number', models.CharField(default='', max_length=255, null=True)),
                ('phone', models.CharField(default='', max_length=255, null=True)),
                ('email', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
    ]
