# Generated by Django 3.2.11 on 2022-04-05 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0086_incidentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_incident_report', to='BP.case'),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='for_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client'),
        ),
    ]
