# Generated by Django 3.2.11 on 2022-04-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0087_auto_20220405_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='fax',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
