# Generated by Django 3.2.11 on 2022-04-05 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0088_incidentreport_fax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_served', models.CharField(default='', max_length=255, null=True)),
                ('due_date', models.CharField(default='', max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('type', models.CharField(default='', max_length=255, null=True)),
                ('for_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_discovery', to='BP.case')),
                ('for_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client')),
                ('from_defendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='give_by_defendant', to='BP.defendant')),
                ('to_defendant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.defendant')),
            ],
        ),
    ]
