# Generated by Django 3.2.11 on 2022-04-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0089_discovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelcasechecklist',
            name='for_defendant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.defendant'),
        ),
    ]
