# Generated by Django 3.2.11 on 2022-04-08 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0091_injury'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injury_cases', to='BP.case'),
        ),
        migrations.AddField(
            model_name='injury',
            name='for_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client'),
        ),
    ]
