# Generated by Django 3.2.11 on 2022-04-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0092_auto_20220408_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='injury',
            name='location',
        ),
        migrations.RemoveField(
            model_name='injury',
            name='specialty',
        ),
        migrations.AddField(
            model_name='injury',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='injury_provider', to='BP.caseproviders'),
        ),
    ]
