# Generated by Django 3.2.11 on 2022-04-08 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0093_auto_20220408_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('date', models.CharField(default='', max_length=255, null=True)),
                ('time', models.CharField(default='', max_length=255, null=True)),
                ('taking', models.CharField(default='', max_length=255, null=True)),
                ('location', models.CharField(default='', max_length=255, null=True)),
                ('address1', models.CharField(default='', max_length=255, null=True)),
                ('address2', models.CharField(default='', max_length=255, null=True)),
                ('city', models.CharField(default='', max_length=255, null=True)),
                ('state', models.CharField(default='', max_length=255, null=True)),
                ('zip_code', models.CharField(default='', max_length=255, null=True)),
                ('note', models.TextField(null=True)),
                ('defending', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deposition_defendants', to='BP.defendant')),
            ],
        ),
    ]
