# Generated by Django 3.2.11 on 2022-04-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0094_deposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposition',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposition_cases', to='BP.case'),
        ),
        migrations.AddField(
            model_name='deposition',
            name='for_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client'),
        ),
    ]
