# Generated by Django 3.2.11 on 2022-04-08 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0095_auto_20220409_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelcasechecklist',
            name='for_otherparty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.otherparty'),
        ),
        migrations.AddField(
            model_name='panelcasechecklist',
            name='for_witness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.witness'),
        ),
    ]
