# Generated by Django 3.2.11 on 2022-04-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0098_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseloan',
            name='current_amount_verified',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='caseloan',
            name='date_verified',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
