# Generated by Django 3.2.11 on 2022-04-15 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0099_auto_20220415_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseloan',
            name='check_number',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caseloan',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='check_number',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='ins_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='reduction',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='write_off',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
