# Generated by Django 3.2.11 on 2022-04-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0105_auto_20220416_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseloan',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
