# Generated by Django 3.2.11 on 2022-04-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0106_alter_caseloan_final_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='final_amount',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
