# Generated by Django 3.2.11 on 2022-04-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0107_alter_offer_final_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_category', to='BP.page'),
        ),
    ]
