# Generated by Django 3.2.11 on 2022-04-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0108_alter_notes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
