# Generated by Django 3.2.11 on 2022-04-19 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BP', '0111_alter_todo_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user_type',
        ),
        migrations.AddField(
            model_name='todo',
            name='todo_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_todo_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
