# Generated by Django 3.2.11 on 2022-04-20 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0112_auto_20220419_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_todo_users', to='BP.attorneystaff'),
        ),
    ]
