# Generated by Django 3.2.11 on 2022-04-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0113_alter_todo_todo_for'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ('created_at',)},
        ),
    ]
