# Generated by Django 3.2.11 on 2022-04-23 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0115_alter_notes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.FileField(null=True, upload_to='images/')),
                ('key', models.FileField(null=True, upload_to='images/')),
                ('form_name', models.CharField(default='', max_length=255, null=True)),
                ('for_state', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('in_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='county_states', to='BP.state')),
            ],
        ),
        migrations.AlterField(
            model_name='litigation',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litigation_county', to='BP.county'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='litigation_states', to='BP.state'),
        ),
    ]
