# Generated by Django 3.2.11 on 2022-04-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0119_alter_courtforms_for_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigation',
            name='court_address1',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='litigation',
            name='court_address2',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='litigation',
            name='court_address_city',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='litigation',
            name='court_address_zip',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
