# Generated by Django 3.2.11 on 2022-04-25 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0120_auto_20220424_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtforms',
            name='for_county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courtform_counties', to='BP.county'),
        ),
    ]
