# Generated by Django 3.2.11 on 2022-04-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0121_courtforms_for_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_url',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('pages', models.ManyToManyField(related_name='casetypes_pages', to='BP.Page')),
            ],
        ),
    ]
