# Generated by Django 3.2.11 on 2022-04-27 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0122_auto_20220427_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BP.casetype'),
        ),
    ]
