# Generated by Django 3.2.11 on 2022-04-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0123_alter_case_case_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, null=True)),
                ('payee', models.CharField(default='', max_length=255, null=True)),
                ('address', models.CharField(default='', max_length=255, null=True)),
                ('address1', models.CharField(default='', max_length=255, null=True)),
                ('city', models.CharField(default='', max_length=255, null=True)),
                ('state', models.CharField(default='', max_length=255, null=True)),
                ('zip_code', models.CharField(default='', max_length=255, null=True)),
                ('phone', models.CharField(default='', max_length=255, null=True)),
                ('extension', models.CharField(default='', max_length=255, null=True)),
                ('fax', models.CharField(default='', max_length=255, null=True)),
                ('email', models.CharField(default='', max_length=255, null=True)),
                ('website', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='incidentreport',
            old_name='reporting_officer',
            new_name='officer_first_name',
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='officer_last_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
