# Generated by Django 3.2.11 on 2022-04-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0124_auto_20220429_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='website',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
