# Generated by Django 3.2.11 on 2022-04-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0125_incidentreport_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='hi_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='hi_reduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='mp_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='original',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='reduction',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
