# Generated by Django 3.2.11 on 2022-04-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0126_auto_20220430_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='court_jurisdiction',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='date_closed',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='firm_users',
            field=models.ManyToManyField(blank=True, related_name='firmusers_cases', to='BP.AttorneyStaff'),
        ),
    ]
