# Generated by Django 3.2.11 on 2022-05-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0130_auto_20220503_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
