# Generated by Django 3.2.11 on 2022-05-03 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0131_incidentreport_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='note',
        ),
        migrations.CreateModel(
            name='IncidentNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('for_incident', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_report_notes', to='BP.incidentreport')),
            ],
        ),
    ]
