# Generated by Django 3.2.11 on 2022-05-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0135_chequerequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorneystaff',
            name='accounting_permission',
            field=models.CharField(blank=True, default='False', max_length=255, null=True),
        ),
    ]
