# Generated by Django 3.2.11 on 2022-05-04 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0136_attorneystaff_accounting_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('cheque_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cheque_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('amount', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('payee', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('memo', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cleared_date', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BP.bankaccounts')),
            ],
        ),
        migrations.CreateModel(
            name='ChequeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='costs',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='check_date',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='check_number',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='costs',
            name='payee',
        ),
        migrations.DeleteModel(
            name='ChequeRequests',
        ),
        migrations.AddField(
            model_name='check',
            name='cheque_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BP.chequetype'),
        ),
        migrations.AddField(
            model_name='costs',
            name='cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BP.check'),
        ),
    ]
