# Generated by Django 3.2.11 on 2022-05-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0137_auto_20220505_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='paid_by',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
