# Generated by Django 3.2.11 on 2022-05-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0138_costs_paid_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='costs',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='payee',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
