# Generated by Django 3.2.11 on 2022-05-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0139_auto_20220505_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
