# Generated by Django 3.2.11 on 2022-05-05 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0140_alter_check_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='cheque',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BP.check'),
        ),
    ]
