# Generated by Django 3.2.11 on 2022-05-05 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0142_check_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_checks', to='BP.case'),
        ),
    ]
