# Generated by Django 3.2.11 on 2022-05-05 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0144_attorneystaff_accounting_admin_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounts',
            name='firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.attorney'),
        ),
    ]
