# Generated by Django 3.2.11 on 2022-05-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0145_bankaccounts_firm'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachBankCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.bankaccounts')),
                ('check_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.chequetype')),
                ('firm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.attorney')),
            ],
        ),
    ]
