# Generated by Django 3.2.11 on 2022-05-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0146_attachbankcheque'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounts',
            name='check_types',
            field=models.ManyToManyField(null=True, to='BP.ChequeType'),
        ),
        migrations.DeleteModel(
            name='AttachBankCheque',
        ),
    ]
