# Generated by Django 3.2.11 on 2022-05-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0147_auto_20220506_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='check_types',
            field=models.ManyToManyField(null=True, related_name='bank_check_types', to='BP.ChequeType'),
        ),
    ]
