# Generated by Django 3.2.11 on 2022-05-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0148_alter_bankaccounts_check_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccounts',
            name='check_types',
            field=models.ManyToManyField(null=True, to='BP.ChequeType'),
        ),
    ]
