# Generated by Django 3.2.11 on 2022-05-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0150_alter_bankaccounts_check_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
