# Generated by Django 3.2.11 on 2022-05-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0151_todo_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='statute',
            name='time',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
