# Generated by Django 3.2.11 on 2022-05-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0154_litigationdetails_enddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='litigationdetails',
            old_name='endDate',
            new_name='end_date',
        ),
    ]
