# Generated by Django 3.2.11 on 2022-05-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0155_rename_enddate_litigationdetails_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statute',
            name='time',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
