# Generated by Django 3.2.11 on 2022-05-18 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_providerstaff_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BP', '0157_alter_notes_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFTodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.CharField(default='', max_length=255, null=True)),
                ('todo_type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('notes', models.CharField(blank=True, default='N/A', max_length=255, null=True)),
                ('status', models.CharField(blank=True, default='Not Completed', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('completed_at', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('completed_note', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('todo_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.attorneystaff')),
            ],
        ),
        migrations.CreateModel(
            name='TFNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('for_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.provider')),
            ],
        ),
    ]
