# Generated by Django 3.2.11 on 2022-05-18 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0158_tfnotes_tftodos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfnotes',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tf_notes_case', to='BP.case'),
        ),
    ]
