# Generated by Django 3.2.11 on 2022-05-18 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_providerstaff_permission'),
        ('BP', '0159_tfnotes_for_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tftodos',
            name='todo_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.providerstaff'),
        ),
    ]
