# Generated by Django 3.2.11 on 2022-05-18 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0160_alter_tftodos_todo_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='tftodos',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tf_todo_case', to='BP.case'),
        ),
    ]
