# Generated by Django 3.2.11 on 2022-05-18 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BP', '0161_tftodos_for_case'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tftodos',
            name='todo_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_for_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
