# Generated by Django 3.2.11 on 2022-05-19 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BP', '0162_alter_tftodos_todo_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_changed_on', models.DateTimeField(auto_now_add=True)),
                ('recent_status', models.TextField(null=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_change_user', to=settings.AUTH_USER_MODEL)),
                ('for_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_request_update', to='BP.case')),
            ],
        ),
    ]
