# Generated by Django 3.2.11 on 2022-05-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0163_requestupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestupdate',
            name='status_changed_on',
            field=models.CharField(default='True', max_length=100, null=True),
        ),
    ]
