# Generated by Django 3.2.11 on 2022-05-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0164_alter_requestupdate_status_changed_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestupdate',
            name='isRequested',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
