# Generated by Django 3.2.11 on 2022-05-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0165_requestupdate_isrequested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestupdate',
            name='isRequested',
            field=models.CharField(default='False', max_length=100, null=True),
        ),
    ]
