# Generated by Django 3.2.11 on 2022-05-19 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0166_alter_requestupdate_isrequested'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestupdate',
            name='requested_at',
            field=models.CharField(default='True', max_length=100, null=True),
        ),
    ]
