# Generated by Django 3.2.11 on 2022-05-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0168_alter_requestupdate_isrequested'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestupdate',
            name='request_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
