# Generated by Django 3.2.11 on 2022-05-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0170_casestage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestage',
            name='case_types',
            field=models.ManyToManyField(blank=True, related_name='casestage_types', to='BP.ClientStatus'),
        ),
    ]
