# Generated by Django 3.2.11 on 2022-05-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0171_alter_casestage_case_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='casestage',
            old_name='case_types',
            new_name='case_statuses',
        ),
    ]
