# Generated by Django 3.2.11 on 2022-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0173_case_case_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casestage',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='casestage',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
