# Generated by Django 3.2.11 on 2022-05-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0175_casetype_user_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attorneystaff',
            name='user_type',
        ),
        migrations.AddField(
            model_name='attorneystaff',
            name='user_type',
            field=models.ManyToManyField(to='BP.AttorneyUserType'),
        ),
    ]
