# Generated by Django 3.2.11 on 2022-05-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0176_auto_20220525_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorneystaff',
            name='team',
            field=models.ManyToManyField(related_name='_BP_attorneystaff_team_+', to='BP.AttorneyStaff'),
        ),
    ]
