# Generated by Django 3.2.11 on 2022-05-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0177_attorneystaff_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorneystaff',
            name='isIntake',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
