# Generated by Django 3.2.11 on 2022-05-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0178_attorneystaff_isintake'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attorneyusertype',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='attorneyusertype',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
