# Generated by Django 3.2.11 on 2022-05-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0180_case_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseproviders',
            name='total_visits',
        ),
        migrations.RemoveField(
            model_name='caseproviders',
            name='visit_from',
        ),
        migrations.RemoveField(
            model_name='caseproviders',
            name='visit_to',
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='first_date',
            field=models.CharField(blank=True, default='_/_/_', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='second_date',
            field=models.CharField(blank=True, default='_/_/_', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='visits',
            field=models.CharField(blank=True, default='__', max_length=100, null=True),
        ),
    ]
