# Generated by Django 3.2.11 on 2022-05-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0181_auto_20220527_0500'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TreatmentNote',
            new_name='TreatmentDates',
        ),
    ]
