# Generated by Django 3.2.11 on 2022-05-31 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0182_rename_treatmentnote_treatmentdates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseproviders',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='caseproviders',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='caseproviders',
            name='ins_paid',
        ),
        migrations.RemoveField(
            model_name='caseproviders',
            name='reduction',
        ),
        migrations.RemoveField(
            model_name='caseproviders',
            name='write_off',
        ),
        migrations.CreateModel(
            name='BPAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hi_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hi_reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mp_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reduction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('for_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_case_accounting', to='BP.case')),
                ('for_case_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_case_provider_accounting', to='BP.caseproviders')),
            ],
        ),
    ]
