# Generated by Django 3.2.11 on 2022-05-31 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0183_auto_20220601_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpaccounting',
            name='for_case_provider',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bp_case_provider_accounting', to='BP.caseproviders'),
        ),
    ]
