# Generated by Django 3.2.11 on 2022-06-15 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20220605_0327'),
        ('BP', '0185_auto_20220601_0502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseproviders',
            name='tf_case_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tf_case_statuses', to='accounts.tfcasestatus'),
        ),
    ]
