# Generated by Django 3.2.11 on 2022-06-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0186_alter_caseproviders_tf_case_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseproviders',
            name='is_open',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
