# Generated by Django 3.2.11 on 2022-07-08 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BP', '0187_caseproviders_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClickRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.IntegerField(blank=True, default=0, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('for_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_record_case', to='BP.case')),
                ('for_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client')),
                ('for_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_record_page', to='BP.page')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_record_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
