# Generated by Django 3.2.11 on 2022-07-24 05:36

import BP.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0187_caseproviders_is_open'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doc_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('y_coord', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('font', models.CharField(choices=[('Courier', 'Courier'), ('Helvetica', 'Helvetica'), ('Times', 'Times')], default='Helvetica', max_length=9)),
                ('font_size', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('line_spacing', models.IntegerField(default=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('target_page', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('template', models.FileField(null=True, upload_to=BP.models.update_filename, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('template_stamped', models.FileField(blank=True, null=True, upload_to=BP.models.update_filename, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('should_update_stamp', models.BooleanField(default=False)),
                ('firm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BP.firm')),
            ],
        ),
    ]
