# Generated by Django 3.2.11 on 2022-07-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0188_clickrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickrecord',
            old_name='date',
            new_name='created_at',
        ),
    ]
