# Generated by Django 3.2.11 on 2022-07-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0189_rename_date_clickrecord_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
