# Generated by Django 3.2.11 on 2022-07-08 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0190_alter_clickrecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickrecord',
            name='for_firm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_record_attorney', to='BP.attorney'),
        ),
    ]
