# Generated by Django 3.2.11 on 2022-07-12 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0192_treatmentgap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentgap',
            name='first_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tf_gap_date1', to='BP.treatmentdates'),
        ),
        migrations.AlterField(
            model_name='treatmentgap',
            name='second_date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tf_gap_date2', to='BP.treatmentdates'),
        ),
    ]
