# Generated by Django 3.2.11 on 2022-07-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0197_alter_hipaadoc_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='hipaadoc',
            name='watermark',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
