# Generated by Django 3.2.11 on 2022-07-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0198_hipaadoc_watermark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hipaadoc',
            name='watermark',
            field=models.FileField(null=True, upload_to='images/watermarks'),
        ),
    ]
