# Generated by Django 3.2.11 on 2022-08-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0200_chatmessage_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='firm',
            name='mailing_email',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firm',
            name='mailing_password',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
