# Generated by Django 3.2.11 on 2022-08-23 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BP', '0201_auto_20220822_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_created_by', to=settings.AUTH_USER_MODEL)),
                ('for_case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_case', to='BP.case')),
                ('for_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_client', to='BP.client')),
            ],
        ),
    ]
