# Generated by Django 3.2.11 on 2022-08-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0204_alter_emails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
