# Generated by Django 3.2.11 on 2022-08-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0205_chatmessage_sender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickrecord',
            name='clickIDName',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
