# Generated by Django 3.2.11 on 2022-09-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0206_clickrecord_clickidname'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='driver_license_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='driver_license_state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ssn',
            field=models.IntegerField(blank=True, default=0, max_length=8, null=True),
        ),
    ]
