# Generated by Django 3.2.11 on 2022-09-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0207_auto_20220903_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ssn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
