# Generated by Django 3.2.11 on 2022-09-07 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0215_alter_click_for_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickrecord',
            name='for_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='click_record_page', to='BP.page'),
        ),
        migrations.AlterField(
            model_name='clickrecord',
            name='click',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Click',
        ),
    ]
