# Generated by Django 3.2.11 on 2022-09-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0216_auto_20220908_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_stage',
        ),
        migrations.AddField(
            model_name='case',
            name='case_stage',
            field=models.ManyToManyField(blank=True, null=True, related_name='case_stages', to='BP.CaseStage'),
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_status',
        ),
        migrations.AddField(
            model_name='case',
            name='case_status',
            field=models.ManyToManyField(blank=True, null=True, related_name='case_statuses', to='BP.ClientStatus'),
        ),
    ]
