# Generated by Django 3.2.11 on 2022-09-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0217_auto_20220909_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_stage',
            field=models.ManyToManyField(blank=True, related_name='case_stages', to='BP.CaseStage'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.ManyToManyField(blank=True, related_name='case_statuses', to='BP.ClientStatus'),
        ),
    ]
