# Generated by Django 3.2.11 on 2022-09-08 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0218_auto_20220909_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='case_stage',
        ),
        migrations.AddField(
            model_name='case',
            name='case_stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_stages', to='BP.casestage'),
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_status',
        ),
        migrations.AddField(
            model_name='case',
            name='case_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_statuses', to='BP.clientstatus'),
        ),
    ]
