# Generated by Django 3.2.11 on 2022-09-08 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0219_auto_20220909_0239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='auto_case_stage',
            field=models.ManyToManyField(blank=True, null=True, related_name='auto_case_stages', to='BP.Stage'),
        ),
        migrations.AddField(
            model_name='case',
            name='auto_case_status',
            field=models.ManyToManyField(blank=True, null=True, related_name='auto_case_statuses', to='BP.Status'),
        ),
    ]
