# Generated by Django 3.2.11 on 2022-09-09 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0222_auto_20220910_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actcasestatus',
            name='stage',
        ),
        migrations.CreateModel(
            name='ActCaseStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='act_case_stage_act', to='BP.act')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='act_case_stage_stage', to='BP.stage')),
            ],
        ),
    ]
