# Generated by Django 3.2.11 on 2022-09-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0223_auto_20220910_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workunit',
            name='less',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workunit',
            name='max',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workunit',
            name='min',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='workunit',
            name='more',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
