# Generated by Django 3.2.11 on 2022-09-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0224_auto_20220910_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workunit',
            name='any_all',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workunit',
            name='empty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workunit',
            name='filled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='workunit',
            name='valued',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
