# Generated by Django 3.2.11 on 2022-09-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0228_workunit_blocked_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workunit',
            name='blocked_status',
            field=models.ManyToManyField(blank=True, related_name='blocked_status_wu', to='BP.Status'),
        ),
    ]
