# Generated by Django 3.2.11 on 2022-09-11 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0229_alter_workunit_blocked_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workunit',
            old_name='any_all',
            new_name='all',
        ),
        migrations.AddField(
            model_name='workunit',
            name='any',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='workunit',
            name='related_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='bpaccounting',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='caraccident',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='casechecklist',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='caseloan',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='caseproviders',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='check',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='costs',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='discovery',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='flaggedpage',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='litigation',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='otherparty',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='panelcasechecklist',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='statute',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='witness',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
    ]
