# Generated by Django 3.2.11 on 2022-09-11 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0230_auto_20220912_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseproviders',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='for_case_caseproviders', to='BP.case'),
        ),
    ]
