# Generated by Django 3.2.11 on 2022-09-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0232_firmthresholdvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmthresholdvalue',
            name='for_firm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm_threshold_values', to='BP.attorney'),
        ),
    ]
