# Generated by Django 3.2.11 on 2022-09-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0233_alter_firmthresholdvalue_for_firm'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='property_damage_value',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
