# Generated by Django 3.2.11 on 2022-09-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0235_attorney_shakespeare_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmthresholdvalue',
            name='max',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='firmthresholdvalue',
            name='min',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
