# Generated by Django 3.2.11 on 2022-09-14 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0236_auto_20220915_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmthresholdvalue',
            old_name='max',
            new_name='property_damage_value_max',
        ),
        migrations.RenameField(
            model_name='firmthresholdvalue',
            old_name='min',
            new_name='property_damage_value_min',
        ),
    ]
