# Generated by Django 3.2.11 on 2022-09-15 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0237_auto_20220915_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='workunit',
            name='checklist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.checklist'),
        ),
    ]
