# Generated by Django 3.2.11 on 2022-09-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0240_todo_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='case_status',
            field=models.ManyToManyField(null=True, to='BP.Status'),
        ),
        migrations.AddField(
            model_name='todo',
            name='daily_workload',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='days_to_repeat',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
