# Generated by Django 3.2.11 on 2022-09-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0241_auto_20220925_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='case_status',
            field=models.ManyToManyField(blank=True, to='BP.Status'),
        ),
    ]
