# Generated by Django 3.2.11 on 2022-09-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0242_alter_todo_case_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='daily_workload',
        ),
    ]
