# Generated by Django 3.2.11 on 2022-09-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0244_auto_20220929_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmrank',
            name='factor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmrank_factor', to='BP.factors'),
        ),
    ]
