# Generated by Django 3.2.11 on 2022-09-28 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0245_alter_firmrank_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firmrank',
            name='factor',
        ),
        migrations.RemoveField(
            model_name='firmrank',
            name='max',
        ),
        migrations.RemoveField(
            model_name='firmrank',
            name='min',
        ),
        migrations.AddField(
            model_name='firmrank',
            name='case_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firmrank_case_type', to='BP.casetype'),
        ),
        migrations.CreateModel(
            name='FactorScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.IntegerField(blank=True, default=0, null=True)),
                ('max', models.IntegerField(blank=True, default=0, null=True)),
                ('factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factorscale_factor', to='BP.factors')),
                ('firm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='factorscale_firm', to='BP.attorney')),
            ],
        ),
        migrations.AddField(
            model_name='firmrank',
            name='factor_scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmrank_factor_scale', to='BP.factorscale'),
        ),
    ]
