# Generated by Django 3.2.11 on 2022-09-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0246_auto_20220929_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_case_rank', to='BP.rank'),
        ),
    ]
