# Generated by Django 3.2.11 on 2022-09-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0248_auto_20220930_2329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='injury',
            old_name='body_part',
            new_name='injury',
        ),
    ]
