# Generated by Django 3.2.11 on 2022-09-30 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0249_rename_body_part_injury_injury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjuster',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='company',
            name='adjusters',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='medpayContact',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='medpayPipLeinContact',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='pipContact',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='propDamContact',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='unInsuredMotoristContact',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='underInsuredMotoristContact',
        ),
        migrations.RenameField(
            model_name='caraccident',
            old_name='accident_note',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='defendant',
            old_name='defendant_note',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='defendant',
            old_name='liability_percent',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='account_number',
            new_name='adjuster_address',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='claim_number',
            new_name='adjuster_email',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='group_number',
            new_name='adjuster_fax',
        ),
        migrations.RenameField(
            model_name='insurance',
            old_name='policy_number',
            new_name='adjuster_phone',
        ),
        migrations.RenameField(
            model_name='otherparty',
            old_name='party_dob',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='otherparty',
            old_name='party_first_name',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='otherparty',
            old_name='party_last_name',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='otherparty',
            old_name='party_middle_name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='otherparty',
            old_name='party_note',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='witness',
            old_name='witness_first_name',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='witness',
            old_name='witness_middle_name',
            new_name='address2',
        ),
        migrations.RenameField(
            model_name='witness',
            old_name='witness_last_name',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='witness',
            old_name='witness_note',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='caraccident',
            name='ClientCarId',
        ),
        migrations.RemoveField(
            model_name='caraccident',
            name='accident_type',
        ),
        migrations.RemoveField(
            model_name='caraccident',
            name='ambulance',
        ),
        migrations.RemoveField(
            model_name='caraccident',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='caraccident',
            name='defendantCarId',
        ),
        migrations.RemoveField(
            model_name='caraccident',
            name='emergencyRoom',
        ),
        migrations.RemoveField(
            model_name='caraccident',
            name='lossOfConc',
        ),
        migrations.RemoveField(
            model_name='caraccident',
            name='reportTaken',
        ),
        migrations.RemoveField(
            model_name='caseloan',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='defendant',
            name='defServedDate',
        ),
        migrations.RemoveField(
            model_name='defendant',
            name='home_contact',
        ),
        migrations.RemoveField(
            model_name='defendant',
            name='liability_insurance_id',
        ),
        migrations.RemoveField(
            model_name='defendant',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='defendant',
            name='work_contact',
        ),
        migrations.RemoveField(
            model_name='injury',
            name='injury',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='ERISAYN',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='UMLimit1',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='UMLimitAll',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='insurance_type',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='lien',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='lienFinal',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='midPayPipLimit',
        ),
        migrations.RemoveField(
            model_name='insurance',
            name='propDamLimit',
        ),
        migrations.RemoveField(
            model_name='otherparty',
            name='party_contact_last',
        ),
        migrations.RemoveField(
            model_name='otherparty',
            name='party_deposition_date',
        ),
        migrations.RemoveField(
            model_name='otherparty',
            name='party_home_contact',
        ),
        migrations.RemoveField(
            model_name='otherparty',
            name='party_served_date',
        ),
        migrations.RemoveField(
            model_name='witness',
            name='witness_birthday',
        ),
        migrations.RemoveField(
            model_name='witness',
            name='witness_contact_home',
        ),
        migrations.RemoveField(
            model_name='witness',
            name='witness_contact_last',
        ),
        migrations.RemoveField(
            model_name='witness',
            name='witness_deposition_date',
        ),
        migrations.RemoveField(
            model_name='witness',
            name='witness_served_date',
        ),
        migrations.AddField(
            model_name='caraccident',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='caraccident',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='caseloan',
            name='address1',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caseloan',
            name='address2',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caseloan',
            name='city',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caseloan',
            name='email',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caseloan',
            name='loan_amount',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caseloan',
            name='phone',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caseloan',
            name='state',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caseloan',
            name='zip_code',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='defendant',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='defendant',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='defendant',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='defendant',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='defendant',
            name='post_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='defendant',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='injury',
            name='body_part',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='adjuster_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='insurance',
            name='claim_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='insurance',
            name='for_defendant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defendant_insurances', to='BP.defendant'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='policy_no',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherparty',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherparty',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherparty',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherparty',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherparty',
            name='post_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='otherparty',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='note',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='post_code',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='company',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='AccidentType',
        ),
        migrations.DeleteModel(
            name='Adjuster',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Injuries',
        ),
        migrations.DeleteModel(
            name='InsuranceType',
        ),
    ]
