# Generated by Django 3.2.11 on 2022-09-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0251_auto_20220930_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='witness_first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='witness',
            name='witness_last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='witness',
            name='witness_middle_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
