# Generated by Django 3.2.11 on 2022-09-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0252_auto_20220930_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witness',
            name='witness_first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='witness',
            name='witness_last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='witness',
            name='witness_middle_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
