# Generated by Django 3.2.11 on 2022-09-30 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0253_auto_20221001_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='for_case',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='for_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client'),
        ),
    ]
