# Generated by Django 3.2.11 on 2022-09-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0254_auto_20221001_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='liabilityLimit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='insurance',
            name='liabilityLimitAll',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
