# Generated by Django 3.2.11 on 2022-09-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0255_auto_20221001_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuster',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adjuster',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='adjuster',
            name='middle_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
