# Generated by Django 3.2.11 on 2022-09-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0256_auto_20221001_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='account_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='claim_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='group_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='policy_number',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
