# Generated by Django 3.2.11 on 2022-09-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0257_auto_20221001_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='liability_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
