# Generated by Django 3.2.11 on 2022-09-30 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BP', '0258_alter_defendant_liability_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentCases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_ids', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recentcases_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
