# Generated by Django 3.2.11 on 2022-10-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0261_auto_20221009_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherparty',
            name='other_party_insurance',
            field=models.ManyToManyField(blank=True, null=True, to='BP.Insurance'),
        ),
        migrations.AlterField(
            model_name='otherparty',
            name='age',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherparty',
            name='driver_license',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherparty',
            name='party_dob',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherparty',
            name='party_note',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='otherparty',
            name='ssn',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
