# Generated by Django 3.2.11 on 2022-10-10 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0268_auto_20221010_0011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancetype',
            name='medpayContact',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='medpayPipLeinContact',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='pipContact',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='propDamContact',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='unInsuredMotoristContact',
        ),
        migrations.RemoveField(
            model_name='insurancetype',
            name='underInsuredMotoristContact',
        ),
        migrations.AddField(
            model_name='insurance',
            name='medpayContact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceType_medpayContact', to='BP.contact'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='medpayPipLeinContact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceType_medpayPipLeinContact', to='BP.contact'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='pipContact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceType_pipContact', to='BP.contact'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='propDamContact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceType_propDamContact', to='BP.contact'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='unInsuredMotoristContact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceType_unInsured', to='BP.contact'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='underInsuredMotoristContact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insuranceType_underInsuredMotoristContact', to='BP.contact'),
        ),
    ]
