# Generated by Django 3.2.11 on 2022-10-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0269_auto_20221010_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='defendant',
            name='defendant_employer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
