# Generated by Django 3.2.11 on 2022-10-11 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0189_alter_doc_template_template'),
        ('BP', '0269_auto_20221010_2227'),
    ]

    operations = [
    ]
