# Generated by Django 3.2.11 on 2022-10-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0270_defendant_defendant_employer'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherparty',
            name='party_employer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='witness',
            name='witness_employer',
            field=models.CharField(default='', max_length=255),
        ),
    ]
