# Generated by Django 3.2.11 on 2022-10-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0271_auto_20221011_2302'),
        ('BP', '0271_auto_20221012_0925'),
    ]

    operations = [
    ]
