# Generated by Django 3.2.11 on 2022-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0272_merge_0271_auto_20221011_2302_0271_auto_20221012_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('order',)},
        ),
        migrations.RemoveField(
            model_name='casetype',
            name='pages',
        ),
        migrations.AddField(
            model_name='page',
            name='case_types',
            field=models.ManyToManyField(blank=True, related_name='page_case_types', to='BP.CaseType'),
        ),
        migrations.AddField(
            model_name='page',
            name='html_template_name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
