# Generated by Django 3.2.11 on 2022-10-15 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0274_alter_defendant_liability_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='claim_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='claim_rejected',
            field=models.CharField(blank=True, default='False', max_length=255),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='defendant_type',
            field=models.CharField(blank=True, default='Private Individual', max_length=255),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='expiry_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='statute_date',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
