# Generated by Django 3.2.11 on 2022-10-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0275_auto_20221016_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defendant',
            name='age',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='birthday',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='claim_rejected',
            field=models.CharField(blank=True, default='False', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='defendant_employer',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='defendant_note',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='defendant_type',
            field=models.CharField(blank=True, default='Private Individual', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='driver_license',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='ssn',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='defendant',
            name='statute_date',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
