# Generated by Django 3.2.11 on 2022-10-15 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0277_page_page_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_icon',
            field=models.FileField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['svg', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
