# Generated by Django 3.2.11 on 2022-10-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0278_alter_page_page_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='StateAbr',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
