# Generated by Django 3.2.11 on 2022-10-19 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0282_auto_20221018_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='primary_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_primary_email', to='BP.contact'),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_primary_phone', to='BP.contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_email', to='BP.contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_phone', to='BP.contact'),
        ),
    ]
