# Generated by Django 3.2.11 on 2022-10-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0283_auto_20221019_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='primary_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_phone',
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
