# Generated by Django 3.2.11 on 2022-10-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0285_auto_20221019_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email',
            new_name='email_contact',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='phone_contact',
        ),
    ]
