# Generated by Django 3.2.11 on 2022-10-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0286_auto_20221019_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='email_contact',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='phone_contact',
            new_name='phone',
        ),
    ]
