# Generated by Django 3.2.11 on 2022-10-19 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0288_auto_20221019_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='phone1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_phone', to='BP.contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
