# Generated by Django 3.2.11 on 2022-10-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0289_auto_20221019_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
