# Generated by Django 3.2.11 on 2022-10-22 15:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0292_auto_20221020_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='check',
            field=models.CharField(blank=True, default='False', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='document_no',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='for_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.case'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='for_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BP.client'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='page_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doc',
            name='provider_documents',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_docs', to='BP.caseproviders'),
        ),
        migrations.AlterField(
            model_name='doc',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
