# Generated by Django 3.2.11 on 2022-10-24 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0283_contact_for_client'),
        ('BP', '0293_auto_20221022_2029'),
    ]

    operations = [
    ]
