# Generated by Django 3.2.11 on 2022-10-24 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0294_merge_0283_contact_for_client_0293_auto_20221022_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='for_client',
        ),
    ]
