# Generated by Django 3.2.11 on 2022-10-24 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0299_rename_middle_name_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_3',
        ),
        migrations.RemoveField(
            model_name='client',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='client',
            name='mailing_contact',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='primary_phone',
        ),
        migrations.RemoveField(
            model_name='client',
            name='title',
        ),
    ]
