# Generated by Django 3.2.11 on 2022-10-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BP', '0304_auto_20221025_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseproviders',
            name='billing_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Billing_Request', to='BP.contact'),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='billing_request_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Billing_Pequest_Paid', to='BP.contact'),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='lien_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Lien_Holder', to='BP.contact'),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='records_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Records_Request', to='BP.contact'),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='records_request_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Records_Request_Paid', to='BP.contact'),
        ),
        migrations.AddField(
            model_name='caseproviders',
            name='treatment_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Treatment_Location', to='BP.contact'),
        ),
    ]
